connection_throttle_limit: -1
connection_throttle: -1
disabled_commands: []
enforce_secure_profile: false
forge_support: false
groups:
  Raraph84:
    - admin
ip_forward: true
listeners:
  - bind_local_address: true
    force_default_server: false
    forced_hosts: {}
    host: 0.0.0.0:25565
    max_players: 0
    motd: "Infinite players on this server?"
    ping_passthrough: false
    priorities: []
    proxy_protocol: false
    query_enabled: false
    query_port: 25577
    tab_list: SERVER
    tab_size: 60
log_commands: true
log_pings: false
network_compression_threshold: 256
online_mode: false
permissions:
  admin:
    - bungeecord.command.alert
    - bungeecord.command.end
    - bungeecord.command.ip
    - bungeecord.command.kick
    - bungeecord.command.list
    - bungeecord.command.reload
    - bungeecord.command.server
  default: []
player_limit: -1
prevent_proxy_connections: false
reject_transfers: false
remote_ping_cache: -1
remote_ping_timeout: 5000
server_connect_timeout: 5000
servers:
  lobby:
    address: 172.17.0.1:25101
    motd: ""
    restricted: false
stats: 80eb5776-ea8f-4f35-99d1-28efb9998d9e
timeout: 30000
